version: "3.9"
services:
  swans-identification-backend:
    build: .
    restart: unless-stopped
    env_file:
      - CONFIG.env
    ports:
      - 5000:5000
    volumes:
      - ./swan_data.db:/app/swan_data.db
